=== fabianlipp/jnami/src/nami/beitrag/namibeitrag.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/namibeitrag/"
	targetNamespace="http://www.example.org/namibeitrag/"
	elementFormDefault="unqualified">

	<element name="namibeitrag" type="tns:namibeitragT" />

	<complexType name="namibeitragT">
		<sequence>
			<element name="database" type="tns:databaseT" maxOccurs="1"
				minOccurs="1" />
			<element name="beitragssaetze" type="tns:beitragssaetzeT"
				maxOccurs="1" minOccurs="1" />
			<element name="sepa" type="tns:sepaT" maxOccurs="1"
				minOccurs="1" />
			<element name="pdfViewer" type="string" maxOccurs="1" minOccurs="1" />
			<element name="letterOutputPath" type="string" maxOccurs="1" minOccurs="1" />
		</sequence>
		<attribute name="gruppierungsnummer" type="string" use="required" />
	</complexType>

	<complexType name="databaseT">
		<all>
			<element name="driver" type="string" maxOccurs="1" minOccurs="1" />
			<element name="url" type="string" maxOccurs="1" minOccurs="1" />
			<element name="username" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="password" type="string" maxOccurs="1"
				minOccurs="0" />
		</all>
	</complexType>

	<complexType name="beitragssaetzeT">
		<sequence>
			<element name="beitragssatz" type="tns:beitragssatzT"
				maxOccurs="unbounded" minOccurs="0" />
		</sequence>

	</complexType>

	<complexType name="beitragssatzT">
		<attribute name="typ" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="VOLLER_BEITRAG" />
					<enumeration value="FAMILIEN_BEITRAG" />
					<enumeration value="SOZIALERMAESSIGUNG" />
					<enumeration value="KEIN_BEITRAG" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="betrag" type="decimal" use="required" />
	</complexType>

	<complexType name="sepaT">
		<all>
			<element name="creditorId" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="lastschriftType" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="mrefPrefix" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="hibiscusUrl" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="hibiscusKontoId" type="integer" maxOccurs="1"
				minOccurs="0" />
		</all>
	</complexType>
</schema>

=== fabianlipp/jnami/doc/namibeitrag.xml
<tns:namibeitrag xmlns:tns="http://www.example.org/namibeitrag/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/namibeitrag/ /home/fabian/eclipse/nami/src/nami/beitrag/namibeitrag.xsd"
	gruppierungsnummer="220309"> <!-- Gruppierungsnummer, für die Beiträge berechnet werden -->

	<!-- Konfiguration der verwendeten SQL-Datenbank -->
	<database>
		<driver>com.mysql.jdbc.Driver</driver>
		<url>jdbc:mysql://localhost:3306/jnamiBeitrag</url>
		<username>jnami</username>
		<password>jnami</password>
	</database>

	<beitragssaetze>
		<beitragssatz typ="VOLLER_BEITRAG" betrag="19.75" />
		<beitragssatz typ="FAMILIEN_BEITRAG" betrag="13.20" />
		<beitragssatz typ="SOZIALERMAESSIGUNG" betrag="6.90" />
		<beitragssatz typ="KEIN_BEITRAG" betrag="0.00" />
	</beitragssaetze>

	<!-- Parameter für SEPA-Lastschriften/für Hibiscus -->
	<sepa>
		<!-- Gläubiger-ID -->
		<creditorId>CRED</creditorId>

		<!-- Art der erzugten Lastschriften (CORE oder COR1) -->
		<lastschriftType>CORE</lastschriftType>

		<!-- Prefix, das bei den Mandatsreferenzen vor der ID eingefügt wird (optional) -->
		<mrefPrefix>M</mrefPrefix>

		<!-- URL zur XML-RPC-Schnittstelle von Hibiscus -->
		<hibiscusUrl>http://localhost:8080/xmlrpc/</hibiscusUrl>

		<!-- Hibiscus-interne ID des verwendeten Girokontos -->
		<hibiscusKontoId>1</hibiscusKontoId>
	</sepa>

	<!-- PDF-Viewer, der zum Betrachten von Briefen aufgerufen wird -->
	<pdfViewer>okular</pdfViewer>

	<!-- Verzeichnis, in dem die Briefe erzeugt werden -->
	<letterOutputPath>/home/user/letterOutput</letterOutputPath>

</tns:namibeitrag>
