=== fabianlipp/jnami/src/nami/statistics/namistatistics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/namistatistics/"
	targetNamespace="http://www.example.org/namistatistics/"
	elementFormDefault="unqualified">
	<element name="namistatistics" type="tns:namistatisticsT"></element>


	<complexType name="namistatisticsT">
		<sequence>
			<element name="database" type="tns:databaseT" maxOccurs="1"
				minOccurs="1"></element>
			<element name="namiconnection" type="tns:namiconnectionT"
				maxOccurs="1" minOccurs="1"></element>
			<element name="gruppe" type="tns:gruppeT" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="databaseT">
		<all>
			<element name="url" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="username" type="string" maxOccurs="1"
				minOccurs="0"></element>
			<element name="password" type="string" maxOccurs="1"
				minOccurs="0"></element>
		</all>
	</complexType>

	<complexType name="namiconnectionT">
		<sequence>
			<element name="credentials" type="tns:credentialsT"
				maxOccurs="1" minOccurs="1"></element>
		</sequence>
		<attribute name="useApi" type="boolean"></attribute>
	</complexType>

	<complexType name="gruppeT">
		<sequence>
			<element name="namiSearch" type="tns:namiSearchT" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
		<attribute name="bezeichnung" type="string" use="required"></attribute>
	</complexType>

	<complexType name="credentialsT">
		<sequence>
			<element name="username" type="string" maxOccurs="1"
				minOccurs="0"></element>
		</sequence>
		<attribute name="type" type="string" use="required"></attribute>
	</complexType>

	<complexType name="namiSearchT">
		<all>
			<element name="taetigkeit" type="tns:idAttributeT" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="untergliederung" type="tns:idAttributeT"
				maxOccurs="1" minOccurs="0">
			</element>
			<element name="mitgliedstyp" type="tns:mitgliedstypT"
				maxOccurs="1" minOccurs="0">
			</element>
		</all>
	</complexType>

	<complexType name="idAttributeT">
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="mitgliedstypT">
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="MITGLIED" />
					<enumeration value="NICHT_MITGLIED" />
					<enumeration value="SCHNUPPER_MITGLIED" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
</schema>

=== fabianlipp/jnami/namistatistics.xml
<tns:namistatistics xmlns:tns="http://www.example.org/namistatistics/"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.example.org/namistatistics/ /home/fabian/eclipse/nami/src/nami/statistics/namistatistics.xsd">
	<database>
		<url>jdbc:mysql://localhost:3306/jnami?useServerPrepStmts=true</url>
		<username>jnami</username> <!-- optional (z. B. bei HSQLDB nicht nötig) -->
		<password>jnami</password>
	</database>
	<namiconnection useApi="false">
		<credentials type="NamiWalletCredentials">
			<!-- alternativ: NamiConsoleCredentials -->
			<username>12345</username> <!-- bei ConsoleCredentials optional -->
		</credentials>
	</namiconnection>
	<gruppe id="1" bezeichnung="Wölflinge">
		<namiSearch>
			<taetigkeit id="1" />
			<untergliederung id="1" />
		</namiSearch>
	</gruppe>
	<gruppe id="2" bezeichnung="Jungpfadfinder">
		<namiSearch>
			<taetigkeit id="1" />
			<untergliederung id="2" />
		</namiSearch>
	</gruppe>
	<gruppe id="3" bezeichnung="Pfadfinder">
		<namiSearch>
			<taetigkeit id="1" />
			<untergliederung id="3" />
		</namiSearch>
	</gruppe>
	<gruppe id="4" bezeichnung="Rover">
		<namiSearch>
			<taetigkeit id="1" />
			<untergliederung id="4" />
		</namiSearch>
	</gruppe>
	<gruppe id="5" bezeichnung="Leiter">
		<namiSearch>
			<taetigkeit id="6" /> <!-- LeiterIn -->
		</namiSearch>
		<namiSearch>
			<taetigkeit id="13" /> <!-- Vorsitzender -->
			<untergliederung id="5" /> <!-- Vorstand -->
		</namiSearch>
		<namiSearch>
			<taetigkeit id="11" /> <!-- Kurat -->
			<untergliederung id="5" /> <!-- Vorstand -->
		</namiSearch>
	</gruppe>
	<gruppe id="6" bezeichnung="Mitglieder">
		<namiSearch>
			<mitgliedstyp id="MITGLIED" />
		</namiSearch>
	</gruppe>
</tns:namistatistics>
